### ISSUE TITLE
Add compatability for multiple media elements on a page

### ISSUE THREAD

**Issue by romulopereira** [vantezzen/skip-silence#1]
If there's a page with more than one video the extension only works with the first. There's a way to solve this?

**Comment by vantezzen** [comment]
Skip-Silence is currently only compatible with one media element per page but I'll mark this as a feature request for your described functionality.

**Comment by romulopereira** [comment]
Thanks

**Comment by vantezzen** [comment]
I released Skip Silence 2 just a few days ago which adds basic support for multiple media elements on a page 🎉
