### ISSUE TITLE
Odysee Incompatible service

### ISSUE THREAD

**Issue by alstrar** [vantezzen/skip-silence#100]
What service is not compatible? (Odysee): ...

Can you provide a link to a specific video where this has occurred? (i.e. can you provide the link where this happend?): https://...

What is the exact problem that occurred? (No sound): ...

What version of Skip Silence are you using? (4): ...

Do you have any other information that might be useful?: Oh, wait. Now it worked. Must have been that I had some changed speed in the video and then the skip-silence(with changed speed as well) on top of that?

**Comment by WofWca** [comment]
May be related to the fact that there are 2 videos on the page - the main one and the ad.
