### ISSUE TITLE
The extension is not available in Firefox Addons

### ISSUE THREAD

**Issue by deevroman** [vantezzen/skip-silence#112]
https://addons.mozilla.org/de/firefox/addon/skip-silence/

**Comment by vantezzen** [comment]
This is a known issue. Mozilla seems to have changed some of their rules and "reevaluated" their decision to approve the extension because they need to build the extension package themselves.

From their mail:
> Details:
We have tried to build your add-on using the provided sources on Ubuntu 18.04.2 using node 16.14.1, npm 8.5.5, but the process aborted with errors.

Their system seems not to be able to compile node-sass, and they won't use the pre-build zip. I'm currently in the process of updating the instructions to work on a clean Debian installation.

**Comment by Raynsauce** [comment]
I'm guessing that's also why you can no longer import skip-silence.zip with "Install extension from file..."

**Comment by vantezzen** [comment]
Yes, loading from debugging should always be possible (otherwise development would also be difficult 😁)
I now created a Docker build setup, which should hopefully allow them to verify the build and bring back the extension to the store this week.

**Comment by vantezzen** [comment]
As an update on this topic: I'm still on this but its unfortunately slow to get the extension through the review process as Mozilla only reports issues after the current issue is fixed.

**Comment by minhmai-codegym** [comment]
Is there any update on this? It is currently still absent in Firefox Addons.

**Comment by vantezzen** [comment]
@minhmai-codegym Unfortunately not really. I've been trying for months now to get this approved but their new review process is an absolute mess. It's not that the extension contains any specific code that triggers this, it's just that they don't follow my build instructions and then reject the version stating that they didn't get the correct output...

I'm currently working on Skip Silence 5 (https://github.com/vantezzen/skip-silence/pull/97) and getting that running on Firefox. Once that is done I'll try if I can get that through the review.

**Comment by deevroman** [comment]
Have you tried asking in their chat? https://matrix.to/#/#addons:mozilla.org Maybe they can give you advice or reviewers will talk to you directly.

**Comment by vantezzen** [comment]
@deevroman I didn't know about that channel, thank you! If these issues still exist when I try to submit the new version I'll try contacting them there

**Comment by Benjamin-Davies** [comment]
I think that part of the problem might be that the `package.json` specifies outdated versions of dependencies. In particular, `node-sass` relies on `node-gyp` which breaks between major node releases, so requires the most up-to-date version to compile properly.

**Comment by vantezzen** [comment]
Yes that was part of the problem as they often used a different Node versions as the one instructed in the build instructions.

The new v5 now uses the correct `sass` package through Plasmo (skip-silence -> plasmo -> @parcel/transformer-sass -> sass) so that shouldn't be a problem anymore - thank you for the info though. I submitted v5 to Firefox Addons yesterday, let's see what their review is.

**Comment by zyatkov** [comment]
Hi! How to install new version? I tried load from "firefox-mv2-prod.zip" but get a error.

**Comment by vantezzen** [comment]
@zyatkov What error are you getting?

**Comment by zyatkov** [comment]
![image](https://user-images.githubusercontent.com/62212913/184174171-148c65bb-bf26-4a03-99eb-764f2117084e.png)

**Comment by vantezzen** [comment]
The addon is still under review in the store so no update there. For anyone trying to install the addon manually, here is a short video tutorial:
![Skip Silence Firefox](https://user-images.githubusercontent.com/10333196/184856859-a1354bc7-7189-4e97-ab3b-bfdd53941517.gif)

**Comment by vantezzen** [comment]
The extension just got approved back into the store 🥳 You can now download it again from https://addons.mozilla.org/de/firefox/addon/skip-silence/

**Comment by JacobTravers** [comment]
I tried to build the addon from source and ran into issues with node-sass as well. I would recommend against using `node-sass` and just using the npm package `sass` if possible, because `node-sass` is deprecated and breaks very often in *nix environments.

**Comment by vantezzen** [comment]
Yeah, as I wrote in https://github.com/vantezzen/skip-silence/issues/112#issuecomment-1211804978, v5 doesn't use `node-sass` anymore and migrated to the recommended `sass`. In part due to this change, Firefox reviews are finally much quicker now.

**Comment by JacobTravers** [comment]
🤦🏽 Ah, I apologize for the spam, I read right up to the comment before that when I should have read the whole thread. Thank you for still responding!
