### ISSUE TITLE
V5 Not saveing settings in chrome.

### ISSUE THREAD

**Issue by RED-404** [vantezzen/skip-silence#125]
**Describe the bug**
After update to V5, its no longer serving any settings.
It does remember that it completed the training screen and the license for dynamic.
Go to a new tab or restart the browser and everything is reset.

**Expected behavior**
Remember settings.

**Desktop (please complete the following information):**
 - OS Arch Linux
 - Browser Google Chrome, Google Chrome (unstable), Thorium Browser, Vivaldi Snapshot
 - Skip Silence Version 5

**Additional context**
I'v also removed the extension and reinstalled it and reactivated my key. 
Still not remembering settings.

**Comment by aeseok** [comment]
experiencing the same thing right now aswell.

**Comment by vantezzen** [comment]
Thank you for your bug report! Just to confirm, do other settings like the playback speed get saved? So its just the license and tutorial status that reset or does all data get reset?

**Comment by RED-404** [comment]
The only thing that gets saved that I can tell is the license info and tutorial status. 
Anything with a toggle, speed settings, and sample threshold gets lost.

**Comment by RED-404** [comment]
Looks like it's fixed with V5.0.8

**Comment by vantezzen** [comment]
> Looks like it's fixed with V5.0.8

Great, I fixed a problem with the persistence but wasn't sure if it was really this bug report. Thank you for testing
