### ISSUE TITLE
Youtube Doesn't Full Screen Properly

### ISSUE THREAD

**Issue by aeseok** [vantezzen/skip-silence#126]
**Describe the bug**
when using the extension (skip silence v5) youtube goes into an expanded theatre mode instead of fullscreening and filling up the whole display.

**To Reproduce**
Just enabling the extension with 1.25x speaking and 3x silence does this for me and any other speed does this.

**Expected behavior**
just fullscreen like how it used to in skip silence v4

**Screenshots**
![Screenshot 2022-08-25 172242](https://user-images.githubusercontent.com/56013980/186581489-24929e37-59d3-435d-90d5-60167cd85657.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Skip Silence Version 5

**Comment by vantezzen** [comment]
Looks like a Chrome bug that has been open for 4 years...

https://bugs.chromium.org/p/chromium/issues/detail?id=836701&q=tabcapture%20fullscreen&can=2

v5 uses the "tabCapture" API on Chrome which allows much better site support but seems to break fullscreen. I'll look into adding an option to switch between how it worked in v4 for fullscreen support but worse site support and v5 with better site support but no fullscreen support

**Comment by vantezzen** [comment]
The next version of Skip silence will come with a selector to choose the recorder type:

![image](https://user-images.githubusercontent.com/10333196/186907240-240af4fe-e9bb-4443-b10e-4fd2b3d7e892.png)

I'm still looking into how this can be presented user-friendly but switching to a different analysis method will solve this issue.
