### ISSUE TITLE
Volunteering for Portuguese translation

### ISSUE THREAD

**Issue by paulovgha** [vantezzen/skip-silence#127]
Hey there Bennett and Skip Silence team, how are you doing?

I'm a software development student and recent user of Skip Silence, and would like to volunteer to help with your update 5 goal of translating the app to other languages. I'm from Brazil, a native Portuguese speaker, and would love to cooperate in the translation and localization as a volunteer, seeing this as an opportunity to network and learn from your projects as I go along in my studies.
Please let me know, and thank you for the great chrome extension, loving it!
Cheers

**Comment by vantezzen** [comment]
Hey Paulo thanks for the offer and welcome! I don't currently have a fancy translation system like CrowdIn setup so all translations are stored in the code.

To add a new translation you can fork this repository and copy the folder under ["/assets/_locales/en"](https://github.com/vantezzen/skip-silence/tree/master/assets/_locales/en) to "/assets/_locales/pt" for the Portuguese translation files.

After that you'll have to translate the messages stored in the "messages.json" file in that folder. You can look at https://github.com/vantezzen/skip-silence/blob/master/assets/_locales/de/messages.json for how this looked like for the german translation I added.

After you've commited your changes to your fork, you can create a Pull Request back to this repository so it is added to the extension.

Let me know if there is anything that you need help with!

**Comment by paulovgha** [comment]
Dear Bennet and Skip Silence team,

Translation submitted. Once integrated in the extension, I'll have another look and make sure to see if there's anything to be corrected, but so far I'm confident the grammar and semantics are are up to par. 

Glad to be a part of this! Cheers!
