### ISSUE TITLE
Please don't console.log in production

### ISSUE THREAD

**Issue by pal03377** [vantezzen/skip-silence#13]
Hi, 

as a developer I frequently use the Chrome Dev Console. Since the last update of this extension, it unfortunately logs out messages, often in a regular interval. Can you remove that from the extension? It is cluttering my console a bit.

To reproduce:  
Go to https://example.com and look into the console.

![messages in the console from Skip Silence](https://user-images.githubusercontent.com/9006596/83980172-dddde100-a913-11ea-81f3-192347ad4228.png)

You can use "Hide messages from main.js" by right-clicking the filename, but that does not seem like a clean solution and the filter generated by this seems to reset itself after some time (or after a Browser restart).
![Don't show main.js console out](https://user-images.githubusercontent.com/9006596/83980197-0cf45280-a914-11ea-8618-4600089f94dc.png)

It seems that `isDebug` is `true` in the current Chrome Webstore version of the extension. 
https://github.com/vantezzen/skip-silence/blob/c1f3cde829490df0b56fb87cf721ae13d43ff5b9/content/main.js#L11

Cheers!

**Comment by vantezzen** [comment]
Thank you for reporting this.
I also already notices that I forgot to update the variable before sending it to Google. Yesterday I released v2.4 which fixes this mistake, but Google is currently taking some time to approve new releases.
