### ISSUE TITLE
Is it possible to return the pro subscription?

### ISSUE THREAD

**Issue by sudo-chan** [vantezzen/skip-silence#131]
I just bought the extension and I don't really like the advantages it provides over the free version. Is it possible to return and invalidate the key?

**Comment by vantezzen** [comment]
Hey, I don't think Gumroad allows self-service refunds but you can write to refunds@vantezzen.io from the mail you bought it with and I'll look into if I can refund it from my dashboard 👍

**Comment by vantezzen** [comment]
Thanks for writing the mail, I just issued a full refund via Gumroad - you should get back your payment in the coming days! Also I didn't invalidate the key, so you should still be able to use the Pro version.

Just out of curiosity, is there anything particular why you wanted the refund? So I know what I can improve in the future

**Comment by sudo-chan** [comment]
TYSM for the refund! Really appreciate it. It was nothing that I didn't really "like". I key reason for me getting the subscription was to use the dynamic threshold. But it turned out that I just loved the manual control more (realized it within a few minutes of using). It does work super well, don't get me wrong. I'm just more of a control freak over most software and hardware I use. Lastly I'm a student so even though I would **love** to support you financially, I'm not in a position to do so. Instead I have shilled your extension to many of my friends and colleagues lol.
