### ISSUE TITLE
The extension appears to include React devtools

### ISSUE THREAD

**Issue by JobLeonard** [vantezzen/skip-silence#138]
**Describe the bug**

Ever since installing the extension I'm seeing the following in my debug console:

```
Error: Could not establish connection. Receiving end does not exist. [contents.04d427ca.js:1:465898](moz-extension://dafeb9ee-ae3f-4623-b81f-16be51147287/contents.04d427ca.js)
```

Clicking opening the url to the file to find its origin shows me this:

![image](https://github.com/vantezzen/skip-silence/assets/259840/4b8e64ff-cb38-4ed0-9373-c4d166045219)

Notice the "Extension (Skip Silence)" in the URL bar.

I've double checked by tracing down the file path to its origin, which indeed turns out to be the Skip Silence `.xpi` file.

**To Reproduce**

1. Open a website
2. Open the devtools
3. Find the described console error

**Desktop:**

 - Linux
 - Firefox 115
 - Skip Silence Version 5

**Additional context**

`contents.js` is 461 KiB of JavaScript. It adds that as dead weight to the extension download. Sure, that's a one-time thing, but it's almost a quarter of the packed `xpi` (and a third of the unpacked content)

![image](https://github.com/vantezzen/skip-silence/assets/259840/abc1fb2a-6b3b-410f-9f88-0dff96441881)

 It also is basically parsed, run and aborted with every website opened, which I'm assuming adds to the latency of a website.

I tried to help out by checking if it's a build config issue - I remember React/WebPack occasionally being a pain in that regard when I still worked with it six years ago, and I was hoping it was just a few lines of easily overlooked config. But I'm not familiar with plasmo and a quick look through its docs doesn't mention anything. Sorry :(

**Comment by WofWca** [comment]
How did you conclude that the build contains React devtools? By looking at the size? Or by looking at the error?

The error is not inherent to React, it's related to Web Extensions API, in particular `browser.runtime.sendMessage()`. The same thing happens with my extension, which doesn't use React.

**Comment by JobLeonard** [comment]
Eh... good question... I think this has likely been a dumb mix-up by me because I was actually debugging a different issue while bumping into this error message. I was actually trying to figure out an unrelated issue on a website built with React (but not mine), and one of the console errors that kept showing an error involving the React DevTools extension (which I apparently had still installed, despite not developing any React app for years). After I uninstalled that this error kept showing up, looking vaguely similar somehow, and because it's mentioning mentioning React in the source file I must have mixed those things up.
