### ISSUE TITLE
Confusing.....

### ISSUE THREAD

**Issue by gmajor78** [vantezzen/skip-silence#20]
So now that I got the extension to activate, no where in the tutorial does it explain how to actually the video once its been edited. Not understanding this at all.....

**Comment by vantezzen** [comment]
Please read the Usage section of this extension's readme (https://github.com/vantezzen/skip-silence#usage) or follow the instructions the plugin gives you directly in the popup.

Basically, just activate the switch in the popup and start the video on the website.
