### ISSUE TITLE
Port to firefox

### ISSUE THREAD

**Issue by praguevara** [vantezzen/skip-silence#24]
I was just wondering if there were any plans to make it work on firefox.

**Comment by vantezzen** [comment]
As written in the readme: "Skip Silence" uses JavaScript's video.playbackRate and MediaSourceElement features simultaneously to achieve its effect. Unfortunately, Firefox currently [has a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1517199) that stops video.playbackRate from working when already using MediaSourceElement - making it impossible for this extension to work on Firefox.
