### ISSUE TITLE
HTML5 Video Tag

### ISSUE THREAD

**Issue by paradoxondev** [vantezzen/skip-silence#29]
What service is not compatible? (e.g. "Vimeo"): HTML5 Video Tag

Can you provide a link to a specific video where this has occurred? (i.e. can you provide the link where this happend?): every video opened direct in the browser

What is the exact problem that occurred? (e.g. "No sound detected" or "No video detected/icon is not green"): No video detected

What version of Skip Silence are you using? (i.e. 1, 2 or 3. You can find this information by opening the popup, it should be right in the title): 3

Problem is probably caused by having a source tag within an video tag instead of a src attribute.

**Comment by vantezzen** [comment]
Cannot reproduce. I've used this code:
```html
<video controls>
      <source src="test.mp4" type="video/mp4">
</video>
```

and it works.

**Comment by pal03377** [comment]
I can reproduce this... Here is a nicer description of how to do it

1. Install Skip Silence in a fresh Chrome browser via the Chrome Web Store
2. Open https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4
3. Click the extension
4. No audio is displayed and silence is not skipped.

Here's what it looks like for me: https://i.imgur.com/Fu2GQwb.mp4

**Comment by vantezzen** [comment]
Very interesting, still can't reproduce it with the exact link you provided: https://imgur.com/a/U7XsuGP

Could you please open the console to see if there are any errors thrown by the extension?

**Comment by pal03377** [comment]
Wow, that's really strange 🤔 

There are no error logs in the console:
![image](https://user-images.githubusercontent.com/9006596/98397043-0737a000-205f-11eb-9f47-1bff096781e3.png)

I'll try to download and install the development version from the repository now and see if I can get more info out of this.

**Comment by pal03377** [comment]
Heyy, I fixed it and it now works locally! The extension didn't search for media elements, as `DOMContentLoaded` event was already fired before it was loaded and the check about whether the event was already fired was incomplete. I completed it in this PR.

**Comment by vantezzen** [comment]
Thank you for researching this and making the PR!
