### ISSUE TITLE
Remember default playback settings

### ISSUE THREAD

**Issue by PacoBell** [vantezzen/skip-silence#30]
**Is your feature request related to a problem? Please describe.**
I'd prefer to play all videos at a certain speed and cadence by default and only have it switched back to normal occasionally.

**Describe the solution you'd like**
Please provide a keyboard hotkey toggle.

**Describe alternatives you've considered**
This extension comes close, but it doesn't actually skip silence.

https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk

**Additional context**
Like this:

![Screenshot 2020-11-03 181512](https://user-images.githubusercontent.com/42870/98061419-b1fe5300-1e00-11eb-80be-008e4955183f.png)

**Comment by PacoBell** [comment]
Oh, uh, maybe you've already thought of this? For some reason, after toggling "Enable Skip Silence" on several videos, it just stays on all the time now, which is fantastic!

**Comment by lijovklm** [comment]
Isn't this addressed here #5?
However, after this new GUI update, I need to set it every time. 
Appreciate if this can be brought back.

**Comment by vantezzen** [comment]
Yes, this was implemented before but as I rewrote the extension, the functionality is not currently implemented anymore. I'll re-implement that in the next few days though
