### ISSUE TITLE
Custom Playback Speed

### ISSUE THREAD

**Issue by bgiesing** [vantezzen/skip-silence#38]
**Is your feature request related to a problem? Please describe.**
I often watch videos on speeds not listed in the app like 2.4x, 3.2x, etc. using an extension called [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk). Because this app only allows setting predefined steps for playback speed, it constantly resets the speed I had picked and I have to manually readjust it.

**Describe the solution you'd like**
Let us type in any speed ratio and possibly add a keybind like the above extension to let us go up in increments of our choosing (0.05, 0.10, 0.20, 1.0, etc) without opening the full panel or command bar. It would eliminate the need to have two conflicting extensions.

**Comment by lijovklm** [comment]
Hi, this would be a welcome feature I can always watch videos in a speed like 1.10 or 1.15. But skip silence has speeds like 1.25, 1.5 etc.

**Comment by vantezzen** [comment]
I have just added a new "Custom" option to the dropdown list:

<img width="356" alt="Screenshot 2021-07-01 at 11 01 35" src="https://user-images.githubusercontent.com/10333196/124097279-b6484200-da5b-11eb-931c-2f9efcde7aa5.png">

Selecting this option will give you a input textbox that you can put any number into:

<img width="194" alt="Screenshot 2021-07-01 at 11 01 57" src="https://user-images.githubusercontent.com/10333196/124097330-c3653100-da5b-11eb-8cc7-7346f2560fb8.png">

Clicking the "Dropdown" button will bring back the normal dropdown view.
