### ISSUE TITLE
Extension not working on YouTube

### ISSUE THREAD

**Issue by PacoBell** [vantezzen/skip-silence#4]
I'm not sure when it started happening, but this extension no longer seems to detect media elements on YouTube. Normally, I would expect to see the icon turn purple and give me playback options, but it doesn't now. For example, I recently tried it on this video in Chrome:

https://www.youtube.com/watch?v=SqcW8kJAMJg

**Comment by KevinNovak** [comment]
I just installed this extension and it's showing as purple on YouTube for me, as well as the link you posted. I'm on Chrome version 83.0.4103.34.

**Comment by vantezzen** [comment]
Sorry for the long delay. I just tested the extension on the video you provided and everything seems to work fine.
Please keep in mind that the extension currently only checks for videos on page load. As YouTube is a single-page webapp, the extension will probably not detect the video when just navigating to it on YouTube. Instead, you'll have to reload the page that contains the video.
This is definately domething that I want to improve in the future.
