### ISSUE TITLE
show speed of video like this

### ISSUE THREAD

**Issue by Eikosa** [vantezzen/skip-silence#44]
![image](https://user-images.githubusercontent.com/20538090/106939151-ed2a5e00-6730-11eb-9939-553b7b670515.png)

**Comment by ochen1** [comment]
Currently, I'm using https://github.com/igrigorik/videospeed to do this.

**Comment by Eikosa** [comment]
yep i am using this too, but wouldn't it be nice if they were all together

**Comment by vantezzen** [comment]
Good idea!

**Comment by vantezzen** [comment]
Closing as this already exists and Chrome recommends to keep extensions functionality more narrow
