### ISSUE TITLE
Save settings

### ISSUE THREAD

**Issue by rithans** [vantezzen/skip-silence#5]
if turned on in any video it works, but when new video selected again it has to be started by clicking icon and as there is no any option to save the applied changes, i need to every time  tune the desired changes.

1. option to auto start on any video.
2. option to save the tuned changes so it dont need to be tuned every time

thank for making such excellent extension

kind regards.

**Comment by techdough** [comment]
totally agreed. great tool this would be awesome.

**Comment by markifi** [comment]
+1

**Comment by vantezzen** [comment]
Starting with the next version of Skip Silence, the extension will save your selected settings 🎉
