### ISSUE TITLE
Synchronisation Problem

### ISSUE THREAD

**Issue by SubGi** [vantezzen/skip-silence#53]
**Describe the bug**
Video and Audio becomes out of sync after some time when using skip silence
**To Reproduce**
Can be tested on any video

**Expected behavior**
Everything should remain in sync throughout the video

**Desktop **
 - OS: [Windows 10]
 - Browser : Chrome
 - Skip Silence Version 3

**Comment by WofWca** [comment]
Duplicate of #28
