### ISSUE TITLE
Firefox Support (since the bug is resolved)

### ISSUE THREAD

**Issue by mrbesher** [vantezzen/skip-silence#54]
[The bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1517199) mentioned as the cause of the lack of Firefox support has been resolved. Is it possible to package the extension for Firefox? Maybe publish it on [AMO](https://addons.mozilla.org)?

**Comment by barolo** [comment]
@vantezzen v91 is in beta currently, just pinging.

**Comment by vantezzen** [comment]
Nice, looks like the resolved bug finally makes Skip Silence run on Firefox > 91:

https://user-images.githubusercontent.com/10333196/125488628-9f69b943-86b5-4e49-8a11-3369fa1a482e.mov

I'm going to add a "strict_min_version" to the extension on Firefox and publish it to the Firefox Addon Store once its released.

For anyone on Firefox Beta 91 that wants to try the extension, you can download the latest build on https://github.com/vantezzen/skip-silence/releases/download/3.4.1/Build.zip and install it on about:debugging#/runtime/this-firefox

**Comment by farnoy** [comment]
I ran a quick test on ff 91.0b1 and it works fine. As a new user, I wish it respected the existing modified playback rate from other extensions though.

**Comment by vantezzen** [comment]
Update: Skip Silence is now also available over the official Firefox Addon Store: https://addons.mozilla.org/de/firefox/addon/skip-silence/

Please note that it still requires Firefox 91 Beta to work

**Comment by barolo** [comment]
Works great for me, under Linux, tested in PiP too.

**Comment by JacobTravers** [comment]
I tried this on Arch Linux with `firefox-developer-edition 91.0b2-1` and I installed the extension both from this repository, and from the firefox addon store and the extension icon doesn't seem to appear anywhere
![image](https://user-images.githubusercontent.com/46337843/126054454-dad56bd4-1e63-4150-90d9-11af1df150ee.png)

**Comment by vantezzen** [comment]
Skip Silence is currently registered as a "page action" instead of a "browser action" (might need to change that in the future) so you should see the icon directly in the URL bar instead:
<img width="567" alt="Screenshot 2021-07-18 at 10 38 28" src="https://user-images.githubusercontent.com/10333196/126061153-7d890089-6822-4061-892a-b57611ae84c5.png">

**Comment by barolo** [comment]
I would prefer it to stay as page action and only to appear on supported pages

**Comment by JacobTravers** [comment]
@vantezzen Ahh I see, I also have a userChrome.css that hides the URL bar unless I hover in that area, had to hover there and then hover the actual URL input to see it, works like a charm! 

PS: thanks for the quick response and great job with this extension, the ui and functionality are excellent. I'd been thinking about how nice this functionality would be on desktop (coming from newpipe on mobile), and I just so happened to finally search it right as the firefox fix came out 🙌🏽 well done!
