### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by yashpalgoyal1304** [vantezzen/skip-silence#56]
hi, sorry i know this is entirely unrelated. But can this abillity be made as an addon for VLC? 

i have the lectures in recorded format so, cant use this extension in this form. i have searched the web, and no solution seems to exist for VLC. it doesnt have waveform support, otherwise i'd have considered using that as an aid in manually skipping silence. 

So... 

sorry again, i just felt a bit helpless regarding vlc's lack of options there.

**Comment by vantezzen** [comment]
Hi, VLC uses a completely different Add-On system and unfortunately I don't have experience with that. You can look at https://wiki.videolan.org/Hacker_Guide/How_To_Write_a_Module/ if you want to create one yourself.

As for local files, you can use the Skip Silence local player at https://vantezzen.github.io/skip-silence/player/ which will simply allow you to open local files in the browser and should allow using Skip Silence (and any other browser extensions) on them.

**Comment by yashpalgoyal1304** [comment]
> As for local files, you can use the Skip Silence local player

Yeah, I thought about using `file:///` or `ftp://` etc, but the web player for those doesn’t have ~~the other seek controls~~ - amh, let’s say it wont work for me. But thanks for sharing. 


> VLC uses a completely different Add-On system and unfortunately I don't have experience with that.

Thanks for the info. Mainly, I wanted to bring this in ur notice for trying if u found time someday (maybe even months later) that it might be worth a shot - as a **related** experiment for the thing which currently has no viable alternate.
