### ISSUE TITLE
Extension "breaks" when it tries playing over 16x.

### ISSUE THREAD

**Issue by dsdsdsdgg** [vantezzen/skip-silence#68]
Love the new custom/faster speeds but Brave (and probably other platforms) can't play above 16x speed. As far as I know this is a browser/chromium limit and not a extension bug.

But with the new speed options, when you select a speed above 16x it "locks" the threshold. Requiring a page refresh to return to normal operation.

System info just in case:
 - Windows 10 64bit
 - Brave 1.26.74 Chromium: 91.0.4472.124
 - Skip Silence 3 (3.4.0)

**Comment by vantezzen** [comment]
Thank you for your bug report.
It looks like browsers cap the Playbackrate between 0.0625 - 16.0 (https://stackoverflow.com/a/32320020).

I'll add those as min and max values of the custom input field so people will get feedback that values higher or lower won't work.

**Comment by dsdsdsdgg** [comment]
👍That should do it.
