### ISSUE TITLE
Skip Silence doesn't work with Opera (with Install Chrome Extensions on)

### ISSUE THREAD

**Issue by Royal-508** [vantezzen/skip-silence#69]
The extension has been doing pretty well since I installed it about a month ago. Unfortunately, yesterday (7.07.2021) it stopped working with my browser at all, along with the new update 3.4.0. 
Even though I use websites like YouTube or Microsoft Stream, the extension's icon remains blank and the user interface of this very extension cannot be opened.
I don't get any particular error messages and the extension appears to be inactive.

 - OS: Win10 64bit
 - Browser: Opera 77.0.4054.172
 - Skip Silence 3, Version 3.4.0

**Comment by Royal-508** [comment]
Updating Opera to 77.0.4054.203 didn't help

**Comment by vantezzen** [comment]
Hey there, thank you for reporting this bug.
Unfortunately, I can't reproduce this bug locally. I installed Skip Silence in Opera from the Chrome Webstore and opened YouTube, but the extension enables correctly:

<img width="1552" alt="Screenshot 2021-07-08 at 10 16 52" src="https://user-images.githubusercontent.com/10333196/124887645-a4bfe680-dfd5-11eb-89d8-b01993827f9a.png">

I am using Skip Silence 3.4.0 and Opera 77.0.4054.203

**Comment by Royal-508** [comment]
Okay, I've sortof found a solution. Deactiviating all extensions except for Skip Silence and Install Chrome Extensions helped and then relaunching my browser. Everything works fine after I don't know if I got the right idea, but I feel it might be a compatibility issue. If a similar situation happens, I'll try to find out which extensions might cause trouble and report it, so that users are warned about incompatibility (considered it's a case).

Thank you for seeing about the issue. I really appreciate it, as I find this extension extremely useful. I truly hope it will continue to reach its target audience and grow in popularity.

**Comment by vantezzen** [comment]
Thank you for testing, yes that sounds like an incompatability with another extension. If you find out which extension it might be, feel free to comment it here - maybe I can solve the incompatability then or at least add a warning to the extension so users know about it.
