### ISSUE TITLE
Add an option to auto re-wind a customizable amount of time after skipping silence

### ISSUE THREAD

**Issue by Tindaer** [vantezzen/skip-silence#70]
I don't know if this suggestion can be implemented, but it could potentially be helpful.

On my system (possibly on others), the higher the speedup on silent parts is, the more of the next "playback speed" part is unintentionally skipped as well.

Up to 4x is no problem, but the higher you go, the more words of the next sentence I miss. Maybe it's a driver issue on my system, but maybe others experience the same thing.

A possible remedy would be to add an option that would combine the mute function with a auto-rewind function with a user-customizable setting.

For example, if someone loses 500ms when setting the silence speed to 10x, the extension would skip the silent part muted, then go back 500ms and start playing unmuted at the "playback speed".

**Comment by Tindaer** [comment]
The planned preload function would render my suggestion obsolete.

Maybe a replacement (like it was in V2) could be implemented later for sites that don't support preloading.

**Comment by lenethx** [comment]
Since the preload function was apparently cancelled, is there any chance this could still be implemented?
