### ISSUE TITLE
Add a counter that shows how much time has been saved

### ISSUE THREAD

**Issue by Johnnycyan** [vantezzen/skip-silence#73]
I would like there to be a counter that shows how much time has been saved by speeding up the video as opposed to if it was played at 1x speed. And for this counter to be persistent across all videos globally.

This idea comes from the extension Sponsorblock which does this for sections it skips.

**Comment by vantezzen** [comment]
This has previously been implemented by #15 but has been removed in Skip Silence 3 due to errors the old implementation had.
I'll look into implementing this again in the future in a way that actually works ^^

**Comment by vantezzen** [comment]
Implemented and will be released with Skip Silence 4

![image](https://user-images.githubusercontent.com/10333196/126786344-1d4e4376-7997-4241-8f5c-bae9ca8cee92.png)
