### ISSUE TITLE
"Command bar icon": css z-index

### ISSUE THREAD

**Issue by nikoked** [vantezzen/skip-silence#78]
**Describe the bug**
"Command bar icon" is below some links on Youtube

**To Reproduce**
1. Open a video on Youtube
2. Expand "Command bar icon" (click the green icon)
2. "Command bar icon" is below some Youtube text

**Expected behavior**
"Command bar icon" should be above everything

**Solution**
Set `z-index: 300;` (or higher) on `<div id="skip-silence-bar">...</div>`

**Comment by vantezzen** [comment]
Thank you for your bug report. I just added a higher z-index to the command bar which should fix this issue.
The fix wil be shipped with the next release.
