### ISSUE TITLE
Solving the skipping problem

### ISSUE THREAD

**Issue by oders** [vantezzen/skip-silence#8]
Hi dear vantezzen,

on trying to build the same plugin I stumbled over yours. Great thanks! :) Saves a lot of time.

I wasn't sure, wether audio analysis could be done right in the browser, so I though of an aproach that might come in handy with the skipping-first-few-frames issue. And wanted to ask for your opinion about it.

It's just cloning the content of the player to a canvas (or using a node-copy) timeshifted.
I.e. doing the analysis in the original player element, which is hidden. And using the results to control the second element which actually gets displayed.

I have another feature Idea, that I will ask for in another Issue :)

Thanks again for the great extension, it is better than I had planned mine :)

**Comment by vantezzen** [comment]
I actually had the same idea (I could upload the code to that to another branch). The problem with this approach is that it works great with standard HTML videos but for sites like YouTube that use blobs instead of simple URLs, I cannot simply clone the media element because I'll get an error.

**Comment by oders** [comment]
Hello and sorry for the delay, I was busy.

Canvas elements can take <video> and <audio> elements as base for the content. This way all kinds of video manipulations are possible on the fily. I haven't tried it with YouTube, but would assume that should work.

I will try that tomorrow, if I find time

There ist

**Comment by vantezzen** [comment]
Closing as this has been implemented in Skip Silence 2
