### ISSUE TITLE
Subtitles and content search

### ISSUE THREAD

**Issue by oders** [vantezzen/skip-silence#9]
Hi dear vantezzen,

me again, proposing another idea :)

Speech recognition combined with a local database to be able to search for phrases in the current and all viewed videos.

My question here would be: 
Do you know a way to do speech recognition in the whole video faster, than normal playback speed (in advance)?

Subtitles could be another benefit.

**Comment by vantezzen** [comment]
Hmm, the only way I could image this is by using something like the Google Cloud Speech-to-Text API but that would require costs for each video processed.

**Comment by oders** [comment]
Hm, for youtube-videos there is also the subtitle API, and for a lot of videos automatic subtitles are available. 
But in general, yes. There is a firefox speech-to-text thing, as far as I remember.. and most probably there are basic javascript solutions

**Comment by vantezzen** [comment]
Closing this as I don't really see it as part of the scope of this extension
